name: Update packages
on:
  workflow_dispatch:
env:
  GIT_AUTHOR_NAME: Foreman Packaging Automation
  GIT_AUTHOR_EMAIL: packaging@theforeman.org

jobs:
  rpm_list:
    name: 'Gather RPMs'
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set_list.outputs.matrix }}
    steps:
    - name: Checkout RPM
      uses: actions/checkout@v2
      with:
        ref: rpm/develop
    - name: Set the list
      id: set_list
      run: ./list_updatable_packages

  bump_rpm:
    name: 'Bump ${{ matrix.package_name }} RPM ${{ matrix.new_version }}'
    needs: rpm_list
    if: needs.rpm_list.outputs.matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.rpm_list.outputs.matrix) }}

    steps:
    - name: Update package
      run: echo "$(basename ${{ matrix.directory }})" --version "${{ matrix.new_version }}"
      
  deb_list:
    name: 'Gather debs'
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set_list.outputs.matrix }}
    steps:
    - name: Checkout deb
      uses: actions/checkout@v2
      with:
        ref: deb/develop
    - name: Set the list
      id: set_list
      run: ./scripts/list_updatable_packages

  bump_plugin_deb:
    name: 'Bump ${{ matrix.package_name }} deb ${{ matrix.new_version }}'
    needs: deb_list
    if: ${{ false }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.deb_list.outputs.matrix) || fromJson('[{"dummy":"true"]') }}
    steps:
    - name: Update package
      run: echo "$(basename ${{ matrix.directory }})" --version "${{ matrix.new_version }}"
